package smartfridge.enu;

public enum TypeActionEnum {

	ADD, 
	REMOVE, 
	REMOVE_EXPIRED, 
	INCREASE_QUANTITY, 
	DECREASE_QUANTITY, 
	CHECK_EXPIRATION, 
	DISPLAY_CONTENT, 
	SORTED_BY_DATE_ADDED, 
	SORTED_BY_DATE_PERISHMENT,
	SORTED_BY_INCREASING_QUANTITY,
	SORTED_BY_DECREASING_QUANTITY,
	SORTED_BY_TYPE,
	UNDO,
	REDO,
	SAVE,
	LOAD,
	EXIT;

}
